### 普通全量上传
POST http://localhost:18086/full/v1/normal
X-File-Total-Size: 102044
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=Boundary12345

--Boundary12345
Content-Disposition: form-data; name="mqttMessageType"

image/png
--Boundary12345
Content-Disposition: form-data; name="upfile"; filename="Base64UploadTest.jpg"

< D:\02-Code\bossfriday\bossfriday-nubybear\cn.bossfriday.fileserver\files\Base64UploadTest.jpg
--Boundary12345