# 系统配置
system:
  # 集群名称（取一个合适的名称即可，ZK根节点以此命名）
  systemName: nubybear
  # ZK地址（多个地址逗号分割）
  zkAddress: localhost:2181
  clusterNode:
    # 节点名称（不重）
    name: cn.bossfriday.im.access-node-1
    # 节点IP
    host: 127.0.0.1
    # 节点RPC端口
    port: 9000
    # 虚拟节点数（路由权重控制使用）
    virtualNodesNum: 100

# 服务配置
service:
  # 接入服务监听端口
  tcpPort: 18080
