system:
  systemName: nubybear
  zkAddress: localhost:2181
  clusterNode:
    name: cn.bossfriday.im.access-node-1
    host: 127.0.0.1
    port: 9000
    virtualNodesNum: 100

service:
  tcpPort: 18080
