### 获取token（鉴权头使用cn.bossfriday.im.sdk.test.tools.ApiTools生成即可）
POST localhost:18081/api/v1/user/getToken
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
X-Timestamp: 1730802500
X-Signature: 2c16a750341affd3e1859a7d568273ac54166a3d
X-Nonce: 56997.4343442391
X-AppKey: 4UKeB5wgkzxzv1K1j

userId=123&deviceId=12143324