System:
  systemName: bossfriday
  zkAddress: localhost:2181
  clusterNode:
    name: bossfriday-node1
    host: 127.0.0.1
    port: 9090
    virtualNodesNum: 100

Global:
  tokenExpireTime: 2592000000

FileServer:
  httpPort: 18086
  storageRootPath: fileData
  cleanerScanInterval: 36000
  namespaces:
    - name: normal
      expireDay: 180
    - name: forever
      expireDay: -1

ImAccess:
  mqttPort: 18080

ImApi:
  httpPort: 18081

DbApRegistration:
  - appId: 100000
    appSecret: "WLYIRU6gHwhUv2"
    secureKey: "gu2VUG0n"
    status: 1
    fileServerAddress: "http://localhost:18086/"
    apiServerAddress: "http://localhost:18081/"