global:
  tokenExpireTime: 2592000000

appRegistration:
  - appId: 100000
    appSecret: "WLYIRU6gHwhUv2"
    secureKey: "gu2VUG0n"
    status: 1
    fileServerAddress: "http://localhost:18086/"
    apiServerAddress: "http://localhost:18081/"