# 系统配置
system:
  systemName: bossfriday
  zkAddress: localhost:2181
  clusterNode:
    name: bossfriday-node1
    host: 127.0.0.1
    port: 9090
    virtualNodesNum: 100

fileServer:
  httpPort: 18086
  storageRootPath: fileData
  cleanerScanInterval: 36000
  namespaces:
    - name: normal
      expireDay: 180
    - name: forever
      expireDay: -1

imAccess:
  mqttPort: 18080

imApi:
  httpPort: 18081
  fileServer: "http://localhost:18086/"